/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request, Response } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FileInterceptor } from "@nestjs/platform-express";
import { PhotoUploadService } from "../photoUpload.service";
import { PhotoUploadCreateInput } from "./PhotoUploadCreateInput";
import { PhotoUpload } from "./PhotoUpload";
import { PhotoUploadFindManyArgs } from "./PhotoUploadFindManyArgs";
import { PhotoUploadWhereUniqueInput } from "./PhotoUploadWhereUniqueInput";
import { PhotoUploadUpdateInput } from "./PhotoUploadUpdateInput";

export class PhotoUploadControllerBase {
  constructor(protected readonly service: PhotoUploadService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PhotoUpload })
  async createPhotoUpload(
    @common.Body() data: PhotoUploadCreateInput
  ): Promise<PhotoUpload> {
    return await this.service.createPhotoUpload({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        imageUrl: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PhotoUpload] })
  @ApiNestedQuery(PhotoUploadFindManyArgs)
  async photoUploads(@common.Req() request: Request): Promise<PhotoUpload[]> {
    const args = plainToClass(PhotoUploadFindManyArgs, request.query);
    return this.service.photoUploads({
      ...args,
      select: {
        createdAt: true,
        id: true,
        imageUrl: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PhotoUpload })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async photoUpload(
    @common.Param() params: PhotoUploadWhereUniqueInput
  ): Promise<PhotoUpload | null> {
    const result = await this.service.photoUpload({
      where: params,
      select: {
        createdAt: true,
        id: true,
        imageUrl: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PhotoUpload })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePhotoUpload(
    @common.Param() params: PhotoUploadWhereUniqueInput,
    @common.Body() data: PhotoUploadUpdateInput
  ): Promise<PhotoUpload | null> {
    try {
      return await this.service.updatePhotoUpload({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          imageUrl: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PhotoUpload })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePhotoUpload(
    @common.Param() params: PhotoUploadWhereUniqueInput
  ): Promise<PhotoUpload | null> {
    try {
      return await this.service.deletePhotoUpload({
        where: params,
        select: {
          createdAt: true,
          id: true,
          imageUrl: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Put(":id/imageUrl")
  @common.UseInterceptors(FileInterceptor("file"))
  @swagger.ApiConsumes("multipart/form-data")
  @swagger.ApiBody({
    schema: {
      type: "object",

      properties: {
        file: {
          type: "string",
          format: "binary",
        },
      },
    },
  })
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiCreatedResponse({
    type: PhotoUpload,
    status: "2XX",
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async uploadImageUrl(
    @common.Param()
    params: PhotoUploadWhereUniqueInput,
    @common.UploadedFile()
    file: Express.Multer.File
  ): Promise<PhotoUpload> {
    return this.service.uploadImageUrl(
      {
        where: params,
      },
      Object.assign(file, {
        filename: file.originalname,
      })
    );
  }

  @common.Get(":id/imageUrl")
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiOkResponse({
    type: common.StreamableFile,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async downloadImageUrl(
    @common.Param()
    params: PhotoUploadWhereUniqueInput,
    @common.Res({
      passthrough: true,
    })
    res: Response
  ): Promise<common.StreamableFile> {
    const result = await this.service.downloadImageUrl({
      where: params,
    });

    if (result === null) {
      throw new errors.NotFoundException(
        "No resource was found for ",
        JSON.stringify(params)
      );
    }

    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${result.filename}`
    );
    res.setHeader("Content-Type", result.mimetype);
    return result.stream;
  }

  @common.Delete(":id/imageUrl")
  @swagger.ApiOkResponse({
    type: PhotoUpload,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async deleteImageUrl(
    @common.Param()
    params: PhotoUploadWhereUniqueInput
  ): Promise<PhotoUpload> {
    return this.service.deleteImageUrl({
      where: params,
    });
  }
}
