/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { BodyMeasurementsFindManyArgs } from "../../bodyMeasurements/base/BodyMeasurementsFindManyArgs";
import { BodyMeasurements } from "../../bodyMeasurements/base/BodyMeasurements";
import { BodyMeasurementsWhereUniqueInput } from "../../bodyMeasurements/base/BodyMeasurementsWhereUniqueInput";
import { PhotoUploadFindManyArgs } from "../../photoUpload/base/PhotoUploadFindManyArgs";
import { PhotoUpload } from "../../photoUpload/base/PhotoUpload";
import { PhotoUploadWhereUniqueInput } from "../../photoUpload/base/PhotoUploadWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: data,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bodyMeasurementsItems")
  @ApiNestedQuery(BodyMeasurementsFindManyArgs)
  async findBodyMeasurementsItems(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<BodyMeasurements[]> {
    const query = plainToClass(BodyMeasurementsFindManyArgs, request.query);
    const results = await this.service.findBodyMeasurementsItems(params.id, {
      ...query,
      select: {
        chest: true,
        createdAt: true,
        height: true,
        hips: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        waist: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bodyMeasurementsItems")
  async connectBodyMeasurementsItems(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: BodyMeasurementsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bodyMeasurementsItems: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bodyMeasurementsItems")
  async updateBodyMeasurementsItems(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: BodyMeasurementsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bodyMeasurementsItems: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bodyMeasurementsItems")
  async disconnectBodyMeasurementsItems(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: BodyMeasurementsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bodyMeasurementsItems: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/photoUploads")
  @ApiNestedQuery(PhotoUploadFindManyArgs)
  async findPhotoUploads(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<PhotoUpload[]> {
    const query = plainToClass(PhotoUploadFindManyArgs, request.query);
    const results = await this.service.findPhotoUploads(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        imageUrl: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/photoUploads")
  async connectPhotoUploads(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: PhotoUploadWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      photoUploads: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/photoUploads")
  async updatePhotoUploads(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: PhotoUploadWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      photoUploads: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/photoUploads")
  async disconnectPhotoUploads(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: PhotoUploadWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      photoUploads: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
