/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { GraphQLUpload } from "graphql-upload";
import { FileUpload } from "src/storage/base/storage.types";
import { ClothingItem } from "./ClothingItem";
import { ClothingItemCountArgs } from "./ClothingItemCountArgs";
import { ClothingItemFindManyArgs } from "./ClothingItemFindManyArgs";
import { ClothingItemFindUniqueArgs } from "./ClothingItemFindUniqueArgs";
import { CreateClothingItemArgs } from "./CreateClothingItemArgs";
import { UpdateClothingItemArgs } from "./UpdateClothingItemArgs";
import { DeleteClothingItemArgs } from "./DeleteClothingItemArgs";
import { ClothingItemService } from "../clothingItem.service";
@graphql.Resolver(() => ClothingItem)
export class ClothingItemResolverBase {
  constructor(protected readonly service: ClothingItemService) {}

  async _clothingItemsMeta(
    @graphql.Args() args: ClothingItemCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ClothingItem])
  async clothingItems(
    @graphql.Args() args: ClothingItemFindManyArgs
  ): Promise<ClothingItem[]> {
    return this.service.clothingItems(args);
  }

  @graphql.Query(() => ClothingItem, { nullable: true })
  async clothingItem(
    @graphql.Args() args: ClothingItemFindUniqueArgs
  ): Promise<ClothingItem | null> {
    const result = await this.service.clothingItem(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ClothingItem)
  async createClothingItem(
    @graphql.Args() args: CreateClothingItemArgs
  ): Promise<ClothingItem> {
    return await this.service.createClothingItem({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => ClothingItem)
  async updateClothingItem(
    @graphql.Args() args: UpdateClothingItemArgs
  ): Promise<ClothingItem | null> {
    try {
      return await this.service.updateClothingItem({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ClothingItem)
  async deleteClothingItem(
    @graphql.Args() args: DeleteClothingItemArgs
  ): Promise<ClothingItem | null> {
    try {
      return await this.service.deleteClothingItem(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ClothingItem)
  async uploadImageUrl(
    @graphql.Args({
      name: "file",
      type: () => GraphQLUpload,
    })
    file: FileUpload,
    @graphql.Args()
    args: ClothingItemFindUniqueArgs
  ): Promise<ClothingItem> {
    return await this.service.uploadImageUrl(args, file);
  }

  @graphql.Mutation(() => ClothingItem)
  async deleteImageUrl(
    @graphql.Args()
    args: ClothingItemFindUniqueArgs
  ): Promise<ClothingItem> {
    return await this.service.deleteImageUrl(args);
  }
}
